# Generated by Django 4.2.7 on 2026-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='文章创建时间'),
        ),
    ]
